name:                soctl
version:             0.1.0.0
github:              "githubuser/soctl"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/soctl#readme>

dependencies:
- base >= 4.7 && < 5
- containers == 0.6.5.1
- http-query == 0.1.3
- text == 1.2.4.1
- aeson == 1.5.6.0 

library:
  source-dirs: src

executables:
  soctl:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - soctl

tests:
  soctl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - soctl
    - hspec == 2.7.10
